const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILURE: 'LOGIN_FAILURE',
};
const LOGOUT = {
  REQUEST: 'LOGOUT_REQUEST',
  SUCCESS: 'LOGOUT_SUCCESS',
  FAILURE: 'LOGOUT_FAILURE',
};

const LOADING = {
  LOADING: 'LOADING',
  SHOW: 'LOADING_SHOW',
  HIDE: 'LOADING_HIDE',
};

const SAVE_USER_DATA = 'SAVE_USER_DATA';
const SAVE_DAY_WORK = 'SAVE_DAY_WORK';
const SAVE_LIST_DAY_WORK = 'SAVE_LIST_DAY_WORK';
const SAVE_DETAIL_COMPANY = 'SAVE_DETAIL_COMPANY';
const SAVE_LIST_ASK_COME_LEAVE = 'SAVE_LIST_ASK_COME_LEAVE';
const CHANGE_LIST_ASK_COME_LEAVE = 'CHANGE_LIST_ASK_COME_LEAVE';
const CHANGE_LIST_CONFIRM_COME_LEAVE = 'CHANGE_LIST_CONFIRM_COME_LEAVE';

const CHANGE_LIST_ASK_DAY_OFF = 'CHANGE_LIST_ASK_DAY_OFF';
const CHANGE_LIST_CONFIRM_DAY_OFF = 'CHANGE_LIST_CONFIRM_DAY_OFF';

export default {
  LOGIN,
  LOADING,
  LOGOUT,
  SAVE_USER_DATA,
  SAVE_DAY_WORK,
  SAVE_LIST_DAY_WORK,
  SAVE_DETAIL_COMPANY,
  SAVE_LIST_ASK_COME_LEAVE,
  CHANGE_LIST_ASK_COME_LEAVE,
  CHANGE_LIST_CONFIRM_COME_LEAVE,
  CHANGE_LIST_ASK_DAY_OFF,
  CHANGE_LIST_CONFIRM_DAY_OFF,
};
