const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILURE: 'LOGIN_FAILURE',
};
const LOGOUT = {
  REQUEST: 'LOGOUT_REQUEST',
  SUCCESS: 'LOGOUT_SUCCESS',
  FAILURE: 'LOGOUT_FAILURE',
};

const LOADING = {
  LOADING: 'LOADING',
  SHOW: 'LOADING_SHOW',
  HIDE: 'LOADING_HIDE',
};

export default {LOGIN, LOADING, LOGOUT};
